### ISSUE TITLE
undefined function put_flash/3 (expected VocialWeb.UserView to define such a function or for it to be imported, but none are available)

### ISSUE THREAD

**Issue by leizhenjiang001** [Goody27/git-training#19]
Reproduction steps
1./Users/zhenjianglei/Desktop/elixir/phoenix/vocial/lib/vocial_web/templates/user/new.html.eex
  Write the following code
 ***************************************************************
<h2>User Signup</h2>
<hr />
<div>
  <%= form_for @user, Routes.user_path(@conn, :create), fn f -> %>
     <%= label f, :username, "Username:" %>
     <br />
     <%= text_input f, :username %>
     <br />
     <%= label f, :email, "Email:" %>
     <br />
     <%= text_input f, :email %>
     <br />
     <%= submit "Sign Up" %>
  <% end %>
</div>
***************************************************************

2./Users/zhenjianglei/Desktop/elixir/phoenix/vocial/lib/vocial_web/controllers/user_controller.ex
   Write the following code
***************************************************************
defmodule VocialWeb.UserController do
  use VocialWeb, :controller

  alias Vocial.Accounts

  #将 conn 上的用户值设置为变更集
  def new(conn, _) do
    user = Accounts.new_user()
    render(conn, "new.html", user: user)
  end

  def create(conn, _) do
    conn
  end

  def show(conn, %{"id" => id}) do
    with user <- Accounts.get_user(id), do: render(conn, "show.html",     user: user)
  end

end

***************************************************************

3./Users/zhenjianglei/Desktop/elixir/phoenix/vocial/lib/vocial_web/router.ex
***************************************************************
defmodule VocialWeb.Router do
  use VocialWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {VocialWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", VocialWeb do
    pipe_through :browser
    get "/polls", PollController, :index
    get "/", PageController, :index
    #现在，这些路由将不起作用，因为它们还没有与之关联的控制器操作。 让我们跳转到我们的 poll_controller.ex 文件并创建新操作：
    get "/polls/new", PollController, :new
    post "/polls", PollController, :create

    get "/users/new", UserController, :new
    get "/users/:id", UserController, :show
    post "/users", UserController, :create

  end

  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: VocialWeb.Telemetry
    end
  end

  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

***************************************************************
4./Users/zhenjianglei/Desktop/elixir/phoenix/vocial/lib/vocial_web.ex
***************************************************************
defmodule VocialWeb do
  def controller do
    quote do
      use Phoenix.Controller, namespace: VocialWeb

      import Plug.Conn
      import VocialWeb.Gettext
      alias VocialWeb.Router.Helpers, as: Routes
    end
  end

  def view do
    quote do
      use Phoenix.View,
        root: "lib/vocial_web/templates",
        namespace: VocialWeb

      # Import convenience functions from controllers
      import Phoenix.Controller,
        only: [get_flash: 1, get_flash: 2, view_module: 1, view_template: 1]

      # Include shared imports and aliases for views
      unquote(view_helpers())
    end
  end

  def live_view do
    quote do
      use Phoenix.LiveView,
        layout: {VocialWeb.LayoutView, "live.html"}

      unquote(view_helpers())
    end
  end

  def live_component do
    quote do
      use Phoenix.LiveComponent

      unquote(view_helpers())
    end
  end

  def component do
    quote do
      use Phoenix.Component

      unquote(view_helpers())
    end
  end

  def router do
    quote do
      use Phoenix.Router

      import Plug.Conn
      import Phoenix.Controller
      import Phoenix.LiveView.Router
    end
  end

  def channel do
    quote do
      use Phoenix.Channel
      import VocialWeb.Gettext
    end
  end

  defp view_helpers do
    quote do
      # Use all HTML functionality (forms, tags, etc)
      use Phoenix.HTML

      # Import LiveView and .heex helpers (live_render, live_patch, <.form>, etc)
      import Phoenix.LiveView.Helpers

      # Import basic rendering functionality (render, render_layout, etc)
      import Phoenix.View

      import VocialWeb.ErrorHelpers
      import VocialWeb.Gettext
      alias VocialWeb.Router.Helpers, as: Routes
    end
  end

  @doc """
  When used, dispatch to the appropriate controller/view/etc.
  """
  defmacro __using__(which) when is_atom(which) do
    apply(__MODULE__, which, [])
  end
end

***************************************************************
There is no problem so far, accessing the link below also shows success
http://localhost:4000//users/new

<img width="632" alt="image" src="https://user-images.githubusercontent.com/111848505/205847755-9d0d3dca-5c97-4491-9b04-83ab34af0aca.png">

5.But after writing the following code, an error occurs:
/Users/zhenjianglei/Desktop/elixir/phoenix/vocial/lib/vocial_web/views/user_view.ex
***************************************************************
defmodule VocialWeb.UserView do
  use VocialWeb, :view

  # 它有一个 use Phoenix.Controller 调用。 这是将导入 put_flash 函数的地方
  def create(conn, %{"user" => user_params}) do
    with {:ok, user} <- Accounts.create_user(user_params) do
      conn
      |> put_flash(:info, "User created!")
      |> redirect(to: user_path(conn, :show, user))
    end
  end

end
***************************************************************

error log:

Compiling 1 file (.ex)

== Compilation error in file lib/vocial_web/views/user_view.ex ==
** (CompileError) lib/vocial_web/views/user_view.ex:14: undefined function put_flash/3 (expected VocialWeb.UserView to define such a function or for it to be imported, but none are available)

Environment

Erlang/OTP 25 [erts-13.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit] [dtrace]

Elixir 1.14.1 (compiled with Erlang/OTP 25)

Phoenix installer v1.6.15

**Comment by leizhenjiang001** [comment]
I rewrote the question and this one is going to be closed

**Comment by conn** [comment]
Glad you're learning git!
